kumuluzee:
  name: smartarticle-articles
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/ArticlesDS
      connection-url: jdbc:postgresql://159.122.187.161:31865/article
      username: dbuser
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/ArticlesDS
  config:
    etcd:
      hosts: http://159.122.187.161:32428
    discovery:
      etcd:
        hosts: http://159.122.187.161:32428
app-properties:
  article-services:
    enabled: true
  healthy: true