kumuluzee:
  name: rso-articles
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/ArticlesDS
      connection-url: jdbc:postgresql://172.17.0.1:5434/article
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://172.17.0.1:2379
    discovery:
      etcd:
        hosts: http://172.17.0.1:2379
app-properties:
  external-services:
    enabled: true