apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article
  template:
    metadata:
      labels:
        app: article
    spec:
      containers:
      - image: ajugo/smartarticle-articles:0.2
        name: article
        imagePullPolicy: "Always"
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://article-db:5432/article
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://159.122.187.161:3046
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: dbuser
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: postgres
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: article
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: article